- name: Setup app servers
  hosts: app_servers
  become: yes
  tasks:
    - name: Add firewall rule for port 80
      firewalld:
        port: 80/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Install prerequisite for nginx
      package:
        name: epel-release
        state: present

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install git
      package:
        name: git
        state: present
