- name: DB server server setup
  hosts: db_servers
  become: yes
  tasks:
  - name: Add inbound firewall rule for port 27017
    firewalld:
      port: 27017/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Create directory for scripts
    file:
      path: /opt/scripts/
      state: directory

  - name: Copy the mongodb installation script to the server
    copy:
      src: ./scripts/db01/
      dest: /opt/scripts/
      mode: 0700

  - name: Copy the db password file
    copy:
      src: ./vault_files/db_password.txt
      dest: /etc/lets_chat_db_password.txt
      mode: 600

  - name: Run the mongodb installation script
    shell: /opt/scripts/mongo_installation.sh

  - name: Create data directory for MongoDB
    file:
      path: /data/db
      state: directory

  - name: Setup authentication for app user in MongoDB
    shell: /opt/scripts/mongo_user_setup.sh

  - name: Start mongod process
    shell: /opt/scripts/mongod_start.sh

