- name: DB server server setup
  hosts: db_servers
  become: yes
  tasks:
  - name: Add inbound firewall rule for port 27017
    firewalld:
      port: 27017/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: Add mongodb repo to yum
    copy:
      src: ./files/db01/mongodb-org-6.0.repo
      dest: /etc/yum.repos.d/mongodb-org-6.0.repo

  - name: Install mongodb
    package:
      name: mongodb-org
      state: present

  - name: Start mongodb service
    service:
      name: mongod
      state: started
      enabled: yes
