- name: K8s master setup
  hosts: "{{ add_hosts }}"
  become: yes
  tasks:
  - name: Add k8s yum repo
    yum_repository:
      name: kubernetes
      description: Kubernetes repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      exclude:
        - kubeadm
        - kubelet
        - kubectl
      gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Adjust SELinux
    shell: setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

  - name: Install kubelet, kudeadm, kubectl
    yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present
      disable_excludes: kubernetes

  - name: Turn swap off
    shell: swapoff -a

  - name: Start kubelet service
    service:
      name: kubelet
      state: started
      enabled: yes

  - name: Add firewall rules
    firewalld:
      port: 6443/tcp
      zone: public
      state: enabled
      permanent: yes
      immediate: yes

  - name: Add firewall rules
    firewalld:
      port: 10250/tcp
      zone: public
      state: enabled
      permanent: yes
      immediate: yes

  - name: Remove config.toml in /etc/containerd
    shell: "[[ -f /etc/containerd/config.toml ]] && mv /etc/containerd/config.toml /etc/containerd/.config.toml"
    ignore_errors: true

  - name: Restart containerd
    service:
      name: containerd
      state: restarted

