- name: Setup k8s master server
  hosts: k8s_masters
  become: yes
  tasks:
  - name: Create scripts directory
    file:
      path: /opt/scripts
      state: directory

  - name: Copy the scripts
    copy:
      src: ./scripts/k8s_master/
      dest: /opt/scripts/

  - name: Add executable permission to the scripts
    shell: chmod +x /opt/scripts/*

