- name: Setup the staging server
  hosts: staging_servers
  become: true
  tasks:
  - name: Set distro name
    set_fact:
      mydistribution: "{{ ansible_distribution | lower }}"

  - name: Add signing key
    rpm_key:
      key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
      state: present

  - name: Add repository into repo.d list
    yum_repository:
      name: docker
      description: docker repository
      baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
      enabled: true
      gpgcheck: true
      gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

  - name: Install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true

  - name: Start docker
    service:
      name: docker
      state: started
      enabled: true

  - name: Install git
    yum:
      name: git
      state: present

  - name: Clone the infrastructure's Github repo
    git:
      repo: https://github.com/Abu-Zakaria/devops-practice-chatty-infra
      dest: /opt/infra
      version: v0.1.0
