- name: Setup the staging server
  hosts: staging_servers
  become: true
  tasks:
  - name: Set distro name
    set_fact:
      mydistribution: "{{ ansible_distribution | lower }}"

  - name: Add signing key
    rpm_key:
      key: "https://download.docker.com/linux/{{ mydistribution }}/gpg"
      state: present

  - name: Add repository into repo.d list
    yum_repository:
      name: docker
      description: docker repository
      baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
      enabled: true
      gpgcheck: true
      gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

  - name: Install docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest
      update_cache: true

  - name: Start docker
    service:
      name: docker
      state: started
      enabled: true

  - name: Install git
    yum:
      name: git
      state: present

  - name: Clone the infrastructure's Github repo
    git:
      repo: https://github.com/Abu-Zakaria/devops-practice-chatty-infra
      dest: /opt/infra

  - name: Copy the db01_ip_address.txt
    copy:
      src: ../db01_ip_address.txt
      dest: /etc/db01_ip_address.txt

  - name: Create secrets directory
    file:
      path: /secrets
      state: directory
      mode: 600

  - name: Copy the db_password.txt
    copy:
      src: ./vault_files/db_password.txt
      dest: /secrets/db_password.txt

  - name: Create scripts directory
    file:
      path: /opt/scripts
      state: directory

  - name: Copy the required scripts
    copy:
      src: ./scripts/app
      dest: /opt/scripts

